# Generated by Django 4.0.5 on 2022-06-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('ug', 'ug'), ('pg', 'pg')], default=0, max_length=4),
        ),
    ]
