# Generated by Django 4.0.5 on 2022-06-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_student_qualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': ' Student'},
        ),
    ]
