# Generated by Django 4.0.5 on 2022-06-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_student_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='MyModel',
        ),
    ]
