# Generated by Django 4.0.5 on 2022-06-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_rename_mymodel_myproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
