# Generated by Django 4.0.5 on 2022-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_alter_myproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
